# ----------------------------------
#          INSTALL & TEST
# ----------------------------------
install_requirements:
	@pip install -r requirements.tx

# ----------------------------------
#      Run frontend
# ----------------------------------
run:
	@streamlit run app.py
