# ----------------------------------
#          INSTALL & TEST
# ----------------------------------
install_requirements:
	@pip install -r requirements.txt

# ----------------------------------
#     		  RUN FRONTEND
# ----------------------------------
run_ui:
	@streamlit run app.py
