import os

AUTOENCODER_LEARNING_RATE=float(os.getenv('AUTOENCODER_LEARNING_RATE'))
AUTOENCODER_N_EPOCHS=int(os.getenv('AUTOENCODER_N_EPOCHS'))
AUTOENCODER_LOSS_FACTOR=int(os.getenv('AUTOENCODER_LOSS_FACTOR'))
CHUNK_SIZE=int(os.getenv('CHUNK_SIZE'))
AUTOENCODER_PATIENCE=int(os.getenv('AUTOENCODER_PATIENCE'))
AUTOENCODER_VALIDATION_SPLIT=float(os.getenv('AUTOENCODER_VALIDATION_SPLIT'))
AUTOENCODER_BATCHSIZE=int(os.getenv('AUTOENCODER_BATCHSIZE'))
AUTOENCODER_LATENT_DIMENSION=int(os.getenv('AUTOENCODER_LATENT_DIMENSION'))
LOCAL_REGISTRY_PATH=os.path.expanduser(os.environ.get('LOCAL_REGISTRY_PATH'))
AUTOENCODER_WIDTH=int(os.getenv('AUTOENCODER_WIDTH'))
AUTOENCODER_HEIGHT=int(os.getenv('AUTOENCODER_HEIGHT'))
LOCAL_DATA_PATH_OUTPUT_IMG=os.path.expanduser(os.environ.get("LOCAL_DATA_PATH_OUTPUT_IMG"))

MODEL_TARGET=os.getenv("MODEL_TARGET")
MLFLOW_TRACKING_URI=os.getenv("MLFLOW_TRACKING_URI")
MLFLOW_MODEL_NAME=os.getenv("MLFLOW_MODEL_NAME")
MLFLOW_EXPERIMENT=os.getenv("MLFLOW_EXPERIMENT")
