import os

STATE_COLUMN_NAME = ['SG_UF']
YEAR_COLUMN_NAME = ['ANO_ELEICAO']
ID_COLUMN_NAME = ['SQ_CANDIDATO']
ELLECTED_COLUMN_NAME = ['DS_SIT_TOT_TURNO']
COLUMN_NAMES = ['NM_CANDIDATO', 'DS_CARGO'] + ID_COLUMN_NAME + ELLECTED_COLUMN_NAME + ['CD_SIT_TOT_TURNO'] + YEAR_COLUMN_NAME + STATE_COLUMN_NAME
FILENAME_COLUMN_NAME = ['filename']
FACE_COLUMN_NAME = ['face']
COLUMN_NAMES_FULL = COLUMN_NAMES + FILENAME_COLUMN_NAME
states = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', 'DF']
ELEITO = ['ELEITO', 'ELEITO POR MÉDIA']
NAO_ELEITO = ['NÃO ELEITO']
CHUNK_SIZE = int(os.environ.get("CHUNK_SIZE"))
LOCAL_DATA_PATH_CSV = os.path.expanduser(os.environ.get("LOCAL_DATA_PATH_CSV"))
LOCAL_DATA_PATH_SRC = os.path.expanduser(os.environ.get("LOCAL_DATA_PATH_SRC"))
LOCAL_DATA_PATH_INPUT_IMG = os.path.expanduser(os.environ.get("LOCAL_DATA_PATH_INPUT_IMG"))
